type Query {
    getOutletConfigData(id: Int!): OutletConfigData @resolver(class: "Vikhyat\\BlogManager\\Model\\Resolver\\Outlet\\OutletConfigData")
}

type Mutation {
    cashierLogin(email: String!, password: String!): CashierData @resolver(class: "Vikhyat\\BlogManager\\Model\\Resolver\\CashierLogin")
}

type OutletConfigData {
    id: Int
    name: String
    source: String
    email: String
    city: String
    region: String
    country: String
    outlet_image: String
    street_line_1: String
    street_line_2: String
    is_active: Int
    website_id: Int
    created_at: String
}

type CashierData {
    id: Int,
    firstname: String,
    lastname: String,
    email: String,
    telephone: String,
    outlet: Int,
    cashier_image: String,
    is_active: Int,
    token: String
}